# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Sat Aug 20 15:20:58 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_timeline = QtGui.QWidget()
        self.tab_timeline.setObjectName(_fromUtf8("tab_timeline"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_timeline)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab_timeline)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.timeline_tree = QtGui.QTreeWidget(self.tab_timeline)
        self.timeline_tree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.timeline_tree.setObjectName(_fromUtf8("timeline_tree"))
        self.timeline_tree.headerItem().setText(0, _fromUtf8("1"))
        self.timeline_tree.header().setVisible(False)
        self.timeline_tree.header().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.timeline_tree)
        self.label = QtGui.QLabel(self.tab_timeline)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.actionlist = QtGui.QListWidget(self.tab_timeline)
        self.actionlist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.actionlist.setAlternatingRowColors(True)
        self.actionlist.setObjectName(_fromUtf8("actionlist"))
        self.verticalLayout_2.addWidget(self.actionlist)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.tab_timeline)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.uid_edit = QtGui.QLineEdit(self.tab_timeline)
        self.uid_edit.setObjectName(_fromUtf8("uid_edit"))
        self.horizontalLayout_5.addWidget(self.uid_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.tab_timeline)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.tags_edit = QtGui.QPlainTextEdit(self.tab_timeline)
        self.tags_edit.setTabChangesFocus(True)
        self.tags_edit.setObjectName(_fromUtf8("tags_edit"))
        self.horizontalLayout_6.addWidget(self.tags_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.label_3 = QtGui.QLabel(self.tab_timeline)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.comment_edit = QtGui.QTextEdit(self.tab_timeline)
        self.comment_edit.setTabChangesFocus(True)
        self.comment_edit.setAcceptRichText(False)
        self.comment_edit.setObjectName(_fromUtf8("comment_edit"))
        self.verticalLayout_3.addWidget(self.comment_edit)
        self.line_2 = QtGui.QFrame(self.tab_timeline)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.label_9 = QtGui.QLabel(self.tab_timeline)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.text_edit = QtGui.QTextEdit(self.tab_timeline)
        self.text_edit.setTabChangesFocus(True)
        self.text_edit.setAcceptRichText(False)
        self.text_edit.setObjectName(_fromUtf8("text_edit"))
        self.verticalLayout_3.addWidget(self.text_edit)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(6, 1)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.timeline_switch = QtGui.QComboBox(self.tab_timeline)
        self.timeline_switch.setObjectName(_fromUtf8("timeline_switch"))
        self.timeline_switch.addItem(_fromUtf8(""))
        self.timeline_switch.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.timeline_switch)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.timeline_stacked = QtGui.QStackedWidget(self.tab_timeline)
        self.timeline_stacked.setObjectName(_fromUtf8("timeline_stacked"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.page)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.role_table = QtGui.QTreeWidget(self.layoutWidget)
        self.role_table.setAlternatingRowColors(True)
        self.role_table.setWordWrap(True)
        self.role_table.setObjectName(_fromUtf8("role_table"))
        self.role_table.header().setDefaultSectionSize(80)
        self.role_table.header().setMinimumSectionSize(80)
        self.verticalLayout_7.addWidget(self.role_table)
        self.layoutWidget_2 = QtGui.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.nodestate_table = QtGui.QTreeWidget(self.layoutWidget_2)
        self.nodestate_table.setAlternatingRowColors(True)
        self.nodestate_table.setWordWrap(True)
        self.nodestate_table.setObjectName(_fromUtf8("nodestate_table"))
        self.nodestate_table.header().setDefaultSectionSize(120)
        self.nodestate_table.header().setMinimumSectionSize(80)
        self.verticalLayout_8.addWidget(self.nodestate_table)
        self.layoutWidget_3 = QtGui.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_9.addWidget(self.label_8)
        self.relationship_table = QtGui.QTreeWidget(self.layoutWidget_3)
        self.relationship_table.setAlternatingRowColors(True)
        self.relationship_table.setWordWrap(True)
        self.relationship_table.setObjectName(_fromUtf8("relationship_table"))
        self.relationship_table.header().setCascadingSectionResizes(False)
        self.relationship_table.header().setDefaultSectionSize(160)
        self.relationship_table.header().setHighlightSections(False)
        self.relationship_table.header().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.relationship_table)
        self.horizontalLayout.addWidget(self.splitter)
        self.timeline_stacked.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_11 = QtGui.QLabel(self.page_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_10.addWidget(self.label_11)
        self.nodestate_view = QtGui.QTreeWidget(self.page_2)
        self.nodestate_view.setAlternatingRowColors(True)
        self.nodestate_view.setObjectName(_fromUtf8("nodestate_view"))
        self.nodestate_view.header().setDefaultSectionSize(120)
        self.nodestate_view.header().setMinimumSectionSize(100)
        self.verticalLayout_10.addWidget(self.nodestate_view)
        self.verticalLayout_10.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.relationship_view = QtGui.QTreeWidget(self.page_2)
        self.relationship_view.setAlternatingRowColors(True)
        self.relationship_view.setObjectName(_fromUtf8("relationship_view"))
        self.relationship_view.header().setDefaultSectionSize(200)
        self.relationship_view.header().setMinimumSectionSize(100)
        self.relationship_view.header().setStretchLastSection(True)
        self.verticalLayout_11.addWidget(self.relationship_view)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 3)
        self.timeline_stacked.addWidget(self.page_2)
        self.verticalLayout_6.addWidget(self.timeline_stacked)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.tabWidget.addTab(self.tab_timeline, _fromUtf8(""))
        self.tab_atom = QtGui.QWidget()
        self.tab_atom.setObjectName(_fromUtf8("tab_atom"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_atom)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_13 = QtGui.QLabel(self.tab_atom)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_10.addWidget(self.label_13)
        self.onto_select = QtGui.QComboBox(self.tab_atom)
        self.onto_select.setObjectName(_fromUtf8("onto_select"))
        self.onto_select.addItem(_fromUtf8(""))
        self.onto_select.addItem(_fromUtf8(""))
        self.onto_select.addItem(_fromUtf8(""))
        self.onto_select.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.onto_select)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.search_button = QtGui.QPushButton(self.tab_atom)
        self.search_button.setObjectName(_fromUtf8("search_button"))
        self.horizontalLayout_10.addWidget(self.search_button)
        self.onto_search = QtGui.QLineEdit(self.tab_atom)
        self.onto_search.setObjectName(_fromUtf8("onto_search"))
        self.horizontalLayout_10.addWidget(self.onto_search)
        self.label_14 = QtGui.QLabel(self.tab_atom)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        self.onto_search_field = QtGui.QComboBox(self.tab_atom)
        self.onto_search_field.setObjectName(_fromUtf8("onto_search_field"))
        self.onto_search_field.addItem(_fromUtf8(""))
        self.onto_search_field.addItem(_fromUtf8(""))
        self.onto_search_field.addItem(_fromUtf8(""))
        self.onto_search_field.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.onto_search_field)
        self.label_15 = QtGui.QLabel(self.tab_atom)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_10.addWidget(self.label_15)
        self.onto_search_rule = QtGui.QComboBox(self.tab_atom)
        self.onto_search_rule.setObjectName(_fromUtf8("onto_search_rule"))
        self.onto_search_rule.addItem(_fromUtf8(""))
        self.onto_search_rule.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.onto_search_rule)
        self.horizontalLayout_10.setStretch(2, 2)
        self.horizontalLayout_10.setStretch(4, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.onto_table = QtGui.QTreeWidget(self.tab_atom)
        self.onto_table.setAlternatingRowColors(True)
        self.onto_table.setColumnCount(3)
        self.onto_table.setObjectName(_fromUtf8("onto_table"))
        self.onto_table.header().setDefaultSectionSize(250)
        self.onto_table.header().setMinimumSectionSize(100)
        self.verticalLayout_14.addWidget(self.onto_table)
        self.tabWidget.addTab(self.tab_atom, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_13.addWidget(self.tabWidget)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.timeline_stacked.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "Timeline:", None))
        self.label.setText(_translate("MainWindow", "Actions:", None))
        self.label_4.setText(_translate("MainWindow", "UID:", None))
        self.label_5.setText(_translate("MainWindow", "Tags:", None))
        self.label_3.setText(_translate("MainWindow", "Comments:", None))
        self.label_9.setText(_translate("MainWindow", "Text:", None))
        self.timeline_switch.setItemText(0, _translate("MainWindow", "Edit action", None))
        self.timeline_switch.setItemText(1, _translate("MainWindow", "View frame", None))
        self.label_6.setText(_translate("MainWindow", "Roles:", None))
        self.role_table.setSortingEnabled(True)
        self.role_table.headerItem().setText(0, _translate("MainWindow", "Role", None))
        self.role_table.headerItem().setText(1, _translate("MainWindow", "Node", None))
        self.label_7.setText(_translate("MainWindow", "Node state changes:", None))
        self.nodestate_table.setSortingEnabled(True)
        self.nodestate_table.headerItem().setText(0, _translate("MainWindow", "Node", None))
        self.nodestate_table.headerItem().setText(1, _translate("MainWindow", "State", None))
        self.label_8.setText(_translate("MainWindow", "Relationship changes:", None))
        self.relationship_table.setSortingEnabled(True)
        self.relationship_table.headerItem().setText(0, _translate("MainWindow", "Nodes", None))
        self.relationship_table.headerItem().setText(1, _translate("MainWindow", "Relation", None))
        self.label_11.setText(_translate("MainWindow", "Node states:", None))
        self.nodestate_view.setSortingEnabled(True)
        self.nodestate_view.headerItem().setText(0, _translate("MainWindow", "Node", None))
        self.nodestate_view.headerItem().setText(1, _translate("MainWindow", "State", None))
        self.label_10.setText(_translate("MainWindow", "Relationships:", None))
        self.relationship_view.setSortingEnabled(True)
        self.relationship_view.headerItem().setText(0, _translate("MainWindow", "Nodes", None))
        self.relationship_view.headerItem().setText(1, _translate("MainWindow", "Relation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_timeline), _translate("MainWindow", "Timeline", None))
        self.label_13.setText(_translate("MainWindow", "Database:", None))
        self.onto_select.setItemText(0, _translate("MainWindow", "Atoms", None))
        self.onto_select.setItemText(1, _translate("MainWindow", "Nodes", None))
        self.onto_select.setItemText(2, _translate("MainWindow", "Actions", None))
        self.onto_select.setItemText(3, _translate("MainWindow", "Events", None))
        self.search_button.setText(_translate("MainWindow", "Search", None))
        self.label_14.setText(_translate("MainWindow", "Field:", None))
        self.onto_search_field.setItemText(0, _translate("MainWindow", "Any", None))
        self.onto_search_field.setItemText(1, _translate("MainWindow", "Source", None))
        self.onto_search_field.setItemText(2, _translate("MainWindow", "Target", None))
        self.onto_search_field.setItemText(3, _translate("MainWindow", "Relation", None))
        self.label_15.setText(_translate("MainWindow", "Rule:", None))
        self.onto_search_rule.setItemText(0, _translate("MainWindow", "Strict", None))
        self.onto_search_rule.setItemText(1, _translate("MainWindow", "Inclusive", None))
        self.onto_table.setSortingEnabled(True)
        self.onto_table.headerItem().setText(0, _translate("MainWindow", "Source", None))
        self.onto_table.headerItem().setText(1, _translate("MainWindow", "Target", None))
        self.onto_table.headerItem().setText(2, _translate("MainWindow", "Content", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_atom), _translate("MainWindow", "Ontologies", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Templates", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))

