# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Sat Aug 20 13:51:23 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1081, 874)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1061, 811))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_timeline = QtGui.QWidget()
        self.tab_timeline.setObjectName(_fromUtf8("tab_timeline"))
        self.label_2 = QtGui.QLabel(self.tab_timeline)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 83, 22))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comment_edit = QtGui.QTextEdit(self.tab_timeline)
        self.comment_edit.setGeometry(QtCore.QRect(220, 140, 781, 71))
        self.comment_edit.setTabChangesFocus(True)
        self.comment_edit.setAcceptRichText(False)
        self.comment_edit.setObjectName(_fromUtf8("comment_edit"))
        self.label_3 = QtGui.QLabel(self.tab_timeline)
        self.label_3.setGeometry(QtCore.QRect(220, 110, 101, 22))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_timeline)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 181, 711))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.timeline_tree = QtGui.QTreeWidget(self.verticalLayoutWidget)
        self.timeline_tree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.timeline_tree.setObjectName(_fromUtf8("timeline_tree"))
        self.timeline_tree.headerItem().setText(0, _fromUtf8("1"))
        self.timeline_tree.header().setVisible(False)
        self.timeline_tree.header().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.timeline_tree)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.actionlist = QtGui.QListWidget(self.verticalLayoutWidget)
        self.actionlist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.actionlist.setAlternatingRowColors(True)
        self.actionlist.setObjectName(_fromUtf8("actionlist"))
        self.verticalLayout.addWidget(self.actionlist)
        self.label_4 = QtGui.QLabel(self.tab_timeline)
        self.label_4.setGeometry(QtCore.QRect(220, 20, 101, 22))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_timeline)
        self.label_5.setGeometry(QtCore.QRect(220, 70, 101, 22))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.uid_edit = QtGui.QLineEdit(self.tab_timeline)
        self.uid_edit.setGeometry(QtCore.QRect(270, 10, 731, 32))
        self.uid_edit.setObjectName(_fromUtf8("uid_edit"))
        self.line_2 = QtGui.QFrame(self.tab_timeline)
        self.line_2.setGeometry(QtCore.QRect(220, 320, 781, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tags_edit = QtGui.QPlainTextEdit(self.tab_timeline)
        self.tags_edit.setGeometry(QtCore.QRect(270, 60, 731, 41))
        self.tags_edit.setTabChangesFocus(True)
        self.tags_edit.setObjectName(_fromUtf8("tags_edit"))
        self.label_9 = QtGui.QLabel(self.tab_timeline)
        self.label_9.setGeometry(QtCore.QRect(220, 240, 101, 71))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.text_edit = QtGui.QTextEdit(self.tab_timeline)
        self.text_edit.setGeometry(QtCore.QRect(290, 240, 711, 71))
        self.text_edit.setTabChangesFocus(True)
        self.text_edit.setAcceptRichText(False)
        self.text_edit.setObjectName(_fromUtf8("text_edit"))
        self.line = QtGui.QFrame(self.tab_timeline)
        self.line.setGeometry(QtCore.QRect(220, 220, 781, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.timeline_stacked = QtGui.QStackedWidget(self.tab_timeline)
        self.timeline_stacked.setGeometry(QtCore.QRect(220, 380, 781, 381))
        self.timeline_stacked.setObjectName(_fromUtf8("timeline_stacked"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.relationship_table = QtGui.QTreeWidget(self.page)
        self.relationship_table.setGeometry(QtCore.QRect(470, 30, 311, 339))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.relationship_table.sizePolicy().hasHeightForWidth())
        self.relationship_table.setSizePolicy(sizePolicy)
        self.relationship_table.setAlternatingRowColors(True)
        self.relationship_table.setWordWrap(True)
        self.relationship_table.setObjectName(_fromUtf8("relationship_table"))
        self.relationship_table.header().setCascadingSectionResizes(False)
        self.relationship_table.header().setDefaultSectionSize(160)
        self.relationship_table.header().setHighlightSections(False)
        self.relationship_table.header().setStretchLastSection(True)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 101, 22))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(240, 0, 181, 22))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.page)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 441, 341))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.role_table = QtGui.QTreeWidget(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.role_table.sizePolicy().hasHeightForWidth())
        self.role_table.setSizePolicy(sizePolicy)
        self.role_table.setAlternatingRowColors(True)
        self.role_table.setWordWrap(True)
        self.role_table.setObjectName(_fromUtf8("role_table"))
        self.role_table.header().setDefaultSectionSize(80)
        self.role_table.header().setMinimumSectionSize(80)
        self.horizontalLayout_4.addWidget(self.role_table)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem)
        self.nodestate_table = QtGui.QTreeWidget(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nodestate_table.sizePolicy().hasHeightForWidth())
        self.nodestate_table.setSizePolicy(sizePolicy)
        self.nodestate_table.setAlternatingRowColors(True)
        self.nodestate_table.setWordWrap(True)
        self.nodestate_table.setObjectName(_fromUtf8("nodestate_table"))
        self.nodestate_table.header().setDefaultSectionSize(80)
        self.nodestate_table.header().setMinimumSectionSize(80)
        self.horizontalLayout_4.addWidget(self.nodestate_table)
        self.label_8 = QtGui.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(470, 0, 201, 22))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.timeline_stacked.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.nodestate_view = QtGui.QTreeWidget(self.page_2)
        self.nodestate_view.setGeometry(QtCore.QRect(0, 30, 281, 339))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nodestate_view.sizePolicy().hasHeightForWidth())
        self.nodestate_view.setSizePolicy(sizePolicy)
        self.nodestate_view.setAlternatingRowColors(True)
        self.nodestate_view.setObjectName(_fromUtf8("nodestate_view"))
        self.nodestate_view.header().setDefaultSectionSize(100)
        self.nodestate_view.header().setMinimumSectionSize(80)
        self.label_10 = QtGui.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(310, 0, 201, 22))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 101, 22))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.relationship_view = QtGui.QTreeWidget(self.page_2)
        self.relationship_view.setGeometry(QtCore.QRect(310, 30, 471, 341))
        self.relationship_view.setAlternatingRowColors(True)
        self.relationship_view.setObjectName(_fromUtf8("relationship_view"))
        self.relationship_view.header().setCascadingSectionResizes(False)
        self.relationship_view.header().setDefaultSectionSize(200)
        self.relationship_view.header().setHighlightSections(False)
        self.relationship_view.header().setStretchLastSection(True)
        self.timeline_stacked.addWidget(self.page_2)
        self.timeline_switch = QtGui.QComboBox(self.tab_timeline)
        self.timeline_switch.setGeometry(QtCore.QRect(860, 340, 141, 32))
        self.timeline_switch.setObjectName(_fromUtf8("timeline_switch"))
        self.timeline_switch.addItem(_fromUtf8(""))
        self.timeline_switch.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_timeline, _fromUtf8(""))
        self.tab_atom = QtGui.QWidget()
        self.tab_atom.setObjectName(_fromUtf8("tab_atom"))
        self.onto_select = QtGui.QComboBox(self.tab_atom)
        self.onto_select.setGeometry(QtCore.QRect(110, 10, 161, 32))
        self.onto_select.setObjectName(_fromUtf8("onto_select"))
        self.onto_select.addItem(_fromUtf8(""))
        self.onto_select.addItem(_fromUtf8(""))
        self.onto_select.addItem(_fromUtf8(""))
        self.onto_select.addItem(_fromUtf8(""))
        self.onto_search = QtGui.QLineEdit(self.tab_atom)
        self.onto_search.setGeometry(QtCore.QRect(510, 10, 221, 32))
        self.onto_search.setObjectName(_fromUtf8("onto_search"))
        self.label_13 = QtGui.QLabel(self.tab_atom)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 91, 22))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_atom)
        self.label_14.setGeometry(QtCore.QRect(750, 20, 83, 22))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.onto_search_field = QtGui.QComboBox(self.tab_atom)
        self.onto_search_field.setGeometry(QtCore.QRect(800, 10, 81, 32))
        self.onto_search_field.setObjectName(_fromUtf8("onto_search_field"))
        self.onto_search_field.addItem(_fromUtf8(""))
        self.onto_search_field.addItem(_fromUtf8(""))
        self.onto_search_field.addItem(_fromUtf8(""))
        self.onto_search_field.addItem(_fromUtf8(""))
        self.onto_table = QtGui.QTreeWidget(self.tab_atom)
        self.onto_table.setGeometry(QtCore.QRect(30, 70, 991, 681))
        self.onto_table.setAlternatingRowColors(True)
        self.onto_table.setColumnCount(3)
        self.onto_table.setObjectName(_fromUtf8("onto_table"))
        self.onto_table.header().setDefaultSectionSize(250)
        self.onto_table.header().setMinimumSectionSize(100)
        self.label_15 = QtGui.QLabel(self.tab_atom)
        self.label_15.setGeometry(QtCore.QRect(890, 20, 83, 22))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.onto_search_rule = QtGui.QComboBox(self.tab_atom)
        self.onto_search_rule.setGeometry(QtCore.QRect(940, 10, 81, 32))
        self.onto_search_rule.setObjectName(_fromUtf8("onto_search_rule"))
        self.onto_search_rule.addItem(_fromUtf8(""))
        self.onto_search_rule.addItem(_fromUtf8(""))
        self.search_button = QtGui.QPushButton(self.tab_atom)
        self.search_button.setGeometry(QtCore.QRect(390, 10, 117, 32))
        self.search_button.setObjectName(_fromUtf8("search_button"))
        self.tabWidget.addTab(self.tab_atom, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.timeline_stacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "Timeline:", None))
        self.label_3.setText(_translate("MainWindow", "Comments:", None))
        self.label.setText(_translate("MainWindow", "Actions:", None))
        self.label_4.setText(_translate("MainWindow", "UID:", None))
        self.label_5.setText(_translate("MainWindow", "Tags:", None))
        self.label_9.setText(_translate("MainWindow", "Text:", None))
        self.relationship_table.setSortingEnabled(True)
        self.relationship_table.headerItem().setText(0, _translate("MainWindow", "Nodes", None))
        self.relationship_table.headerItem().setText(1, _translate("MainWindow", "Relation", None))
        self.label_6.setText(_translate("MainWindow", "Roles:", None))
        self.label_7.setText(_translate("MainWindow", "Node state changes:", None))
        self.role_table.setSortingEnabled(True)
        self.role_table.headerItem().setText(0, _translate("MainWindow", "Role", None))
        self.role_table.headerItem().setText(1, _translate("MainWindow", "Node", None))
        self.nodestate_table.setSortingEnabled(True)
        self.nodestate_table.headerItem().setText(0, _translate("MainWindow", "Node", None))
        self.nodestate_table.headerItem().setText(1, _translate("MainWindow", "State", None))
        self.label_8.setText(_translate("MainWindow", "Relationship changes:", None))
        self.nodestate_view.setSortingEnabled(True)
        self.nodestate_view.headerItem().setText(0, _translate("MainWindow", "Node", None))
        self.nodestate_view.headerItem().setText(1, _translate("MainWindow", "State", None))
        self.label_10.setText(_translate("MainWindow", "Relationships:", None))
        self.label_11.setText(_translate("MainWindow", "Node states:", None))
        self.relationship_view.setSortingEnabled(True)
        self.relationship_view.headerItem().setText(0, _translate("MainWindow", "Nodes", None))
        self.relationship_view.headerItem().setText(1, _translate("MainWindow", "Relation", None))
        self.timeline_switch.setItemText(0, _translate("MainWindow", "Edit action", None))
        self.timeline_switch.setItemText(1, _translate("MainWindow", "View frame", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_timeline), _translate("MainWindow", "Timeline", None))
        self.onto_select.setItemText(0, _translate("MainWindow", "Atoms", None))
        self.onto_select.setItemText(1, _translate("MainWindow", "Nodes", None))
        self.onto_select.setItemText(2, _translate("MainWindow", "Actions", None))
        self.onto_select.setItemText(3, _translate("MainWindow", "Events", None))
        self.label_13.setText(_translate("MainWindow", "Database:", None))
        self.label_14.setText(_translate("MainWindow", "Field:", None))
        self.onto_search_field.setItemText(0, _translate("MainWindow", "Any", None))
        self.onto_search_field.setItemText(1, _translate("MainWindow", "Source", None))
        self.onto_search_field.setItemText(2, _translate("MainWindow", "Target", None))
        self.onto_search_field.setItemText(3, _translate("MainWindow", "Relation", None))
        self.onto_table.setSortingEnabled(True)
        self.onto_table.headerItem().setText(0, _translate("MainWindow", "Source", None))
        self.onto_table.headerItem().setText(1, _translate("MainWindow", "Target", None))
        self.onto_table.headerItem().setText(2, _translate("MainWindow", "Content", None))
        self.label_15.setText(_translate("MainWindow", "Rule:", None))
        self.onto_search_rule.setItemText(0, _translate("MainWindow", "Strict", None))
        self.onto_search_rule.setItemText(1, _translate("MainWindow", "Inclusive", None))
        self.search_button.setText(_translate("MainWindow", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_atom), _translate("MainWindow", "Ontologies", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Templates", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))

